platform :ios, '7.0'

target 'HCKitProject' do
   pod 'FMDB', '~> 2.7'
   pod 'AFNetworking', '~> 4'
#   pod 'SIAlertView', '~> 1.3'
#   pod 'SVProgressHUD', '~> 2.0.3'
#   pod 'Masonry', '~> 1.0.1'

end
