# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HCKitSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FMDB', '~> 2.5'

  target 'HCKitSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HCKitSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
