# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HCKitSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
#	pod 'HCKitProject/Core', :git => 'https://github.com/huachen206/HCKitProject.git'
#	pod 'HCKitProject/HCDB', :git => 'https://github.com/huachen206/HCKitProject.git'

  target 'HCKitSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HCKitSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
